server:
  port: 80

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


kakao:
  dapi:
    host: https://dapi.kakao.com
  rest:
    api:
      key: 06533fa265c5dc96e4fcfec9aad83d71

naver:
  openapi:
    host: https://openapi.naver.com
  client:
    id: c0hvQAp5FCMelYR3mKAr
    secret: NmpoBjKncq
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jpa.bind: trace